"""Pydantic request/response schemas."""

from precursor.backend.schemas.agent import (
    AgentEvent,
    AgentLinkRequest,
    AgentPermissionDecision,
    AgentSendRequest,
    AgentSessionCreate,
    AgentSessionRead,
)
from precursor.backend.schemas.chat import (
    ChatCreate,
    ChatRead,
    ChatUpdate,
)
from precursor.backend.schemas.meeting import (
    MeetingAskRequest,
    MeetingInsightRead,
    MeetingSegmentCreate,
    MeetingSegmentRead,
    MeetingSessionCreate,
    MeetingSessionRead,
    MeetingSessionUpdate,
    MeetingSummaryPost,
    MeetingSummaryPostResult,
    MeetingSummaryResult,
)
from precursor.backend.schemas.memory import (
    MemoryCreate,
    MemoryRead,
    MemoryUpdate,
)
from precursor.backend.schemas.message import (
    AttachmentRead,
    ChatRequest,
    MessageCreate,
    MessageRead,
    NoteDraftAttachmentRead,
    StoppedTurn,
)
from precursor.backend.schemas.role import (
    RoleCreate,
    RoleRead,
    RoleUpdate,
)
from precursor.backend.schemas.settings import SettingsPayload, SettingsRead
from precursor.backend.schemas.skill import (
    SkillCreate,
    SkillRead,
    SkillUpdate,
)
from precursor.backend.schemas.stats import UsageBucket, UsageStats
from precursor.backend.schemas.topic import (
    TopicCreate,
    TopicNode,
    TopicRead,
    TopicUpdate,
)
from precursor.backend.schemas.workspace import (
    CommitRequest,
    FileContent,
    FileCreate,
    FileDiff,
    FileNode,
    FileRename,
    FileWrite,
    FolderCreate,
    GitActionResult,
    GitStatus,
    LocalPath,
    WorkspaceCreate,
    WorkspaceRead,
    WorkspaceUpdate,
)

__all__ = [
    "AgentEvent",
    "AgentLinkRequest",
    "AgentPermissionDecision",
    "AgentSendRequest",
    "AgentSessionCreate",
    "AgentSessionRead",
    "AttachmentRead",
    "ChatCreate",
    "ChatRead",
    "ChatRequest",
    "ChatUpdate",
    "CommitRequest",
    "FileContent",
    "FileCreate",
    "FileDiff",
    "FileNode",
    "FileRename",
    "FileWrite",
    "FolderCreate",
    "GitActionResult",
    "GitStatus",
    "LocalPath",
    "MeetingAskRequest",
    "MeetingInsightRead",
    "MeetingSegmentCreate",
    "MeetingSegmentRead",
    "MeetingSessionCreate",
    "MeetingSessionRead",
    "MeetingSessionUpdate",
    "MeetingSummaryPost",
    "MeetingSummaryPostResult",
    "MeetingSummaryResult",
    "MemoryCreate",
    "MemoryRead",
    "MemoryUpdate",
    "MessageCreate",
    "MessageRead",
    "NoteDraftAttachmentRead",
    "RoleCreate",
    "RoleRead",
    "RoleUpdate",
    "SettingsPayload",
    "SettingsRead",
    "SkillCreate",
    "SkillRead",
    "SkillUpdate",
    "StoppedTurn",
    "TopicCreate",
    "TopicNode",
    "TopicRead",
    "TopicUpdate",
    "UsageBucket",
    "UsageStats",
    "WorkspaceCreate",
    "WorkspaceRead",
    "WorkspaceUpdate",
]
