"""add note draft attachments

Revision ID: 0c1254639726
Revises: cf7e6a63db17
Create Date: 2026-06-19 15:03:46.625235

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0c1254639726"
down_revision: str | None = "cf7e6a63db17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note_draft_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_draft_id", sa.Integer(), nullable=False),
        sa.Column("mime", sa.String(length=127), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["note_draft_id"], ["note_drafts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_note_draft_attachments_note_draft_id"),
        "note_draft_attachments",
        ["note_draft_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_note_draft_attachments_note_draft_id"), table_name="note_draft_attachments"
    )
    op.drop_table("note_draft_attachments")
    # ### end Alembic commands ###
