"""add agent_sessions

Revision ID: 0fd63760742a
Revises: 0c1254639726
Create Date: 2026-06-23 12:02:30.312069

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0fd63760742a"
down_revision: str | None = "0c1254639726"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("copilot_session_id", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("task_prompt", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (topic_id IS NOT NULL AND chat_id IS NOT NULL)", name="ck_agent_session_container"
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_sessions_chat_id"), "agent_sessions", ["chat_id"], unique=False)
    op.create_index(
        op.f("ix_agent_sessions_copilot_session_id"),
        "agent_sessions",
        ["copilot_session_id"],
        unique=True,
    )
    op.create_index(op.f("ix_agent_sessions_status"), "agent_sessions", ["status"], unique=False)
    op.create_index(
        op.f("ix_agent_sessions_topic_id"), "agent_sessions", ["topic_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_sessions_topic_id"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_status"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_copilot_session_id"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_chat_id"), table_name="agent_sessions")
    op.drop_table("agent_sessions")
    # ### end Alembic commands ###
