"""add meeting_attachments table

Revision ID: 22ce95ab9f0a
Revises: 9633c13db421
Create Date: 2026-07-12 12:43:17.356016

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "22ce95ab9f0a"
down_revision: str | None = "9633c13db421"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meeting_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("mime", sa.String(length=127), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["meeting_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meeting_attachments_session_id"),
        "meeting_attachments",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meeting_attachments_sha256"), "meeting_attachments", ["sha256"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meeting_attachments_sha256"), table_name="meeting_attachments")
    op.drop_index(op.f("ix_meeting_attachments_session_id"), table_name="meeting_attachments")
    op.drop_table("meeting_attachments")
    # ### end Alembic commands ###
