"""add agent_events timeline archive

Revision ID: 2b00968ac335
Revises: 7ef20a82eb10
Create Date: 2026-06-23 17:42:03.086799

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2b00968ac335"
down_revision: str | None = "7ef20a82eb10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_session_id", sa.Integer(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_session_id"], ["agent_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_events_agent_session_id"), "agent_events", ["agent_session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_events_agent_session_id"), table_name="agent_events")
    op.drop_table("agent_events")
    # ### end Alembic commands ###
