"""meeting session attendees

Revision ID: 2ec08130160f
Revises: 5c8e2aeaa48d
Create Date: 2026-07-11 18:22:29.255213

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2ec08130160f"
down_revision: str | None = "5c8e2aeaa48d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting_sessions",
        sa.Column("attendees_json", sa.Text(), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting_sessions", "attendees_json")
    # ### end Alembic commands ###
