"""add context_notes_json to meeting_sessions

Revision ID: 38e2b7f39f6c
Revises: 4cc067ddf339
Create Date: 2026-07-12 12:19:31.833961

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "38e2b7f39f6c"
down_revision: str | None = "4cc067ddf339"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting_sessions",
        sa.Column("context_notes_json", sa.Text(), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting_sessions", "context_notes_json")
    # ### end Alembic commands ###
