"""meeting session external meeting link

Revision ID: 4cc067ddf339
Revises: 2ec08130160f
Create Date: 2026-07-11 18:34:42.993614

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4cc067ddf339"
down_revision: str | None = "2ec08130160f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meeting_sessions", sa.Column("external_meeting_json", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting_sessions", "external_meeting_json")
    # ### end Alembic commands ###
