"""add meeting session archiving

Revision ID: 4fbf2183a9da
Revises: f4d0de85d7e4
Create Date: 2026-07-15 18:06:36.922602

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4fbf2183a9da"
down_revision: str | None = "f4d0de85d7e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting_sessions", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting_sessions", "archived_at")
    # ### end Alembic commands ###
