"""meeting session speaker names map

Revision ID: 5c8e2aeaa48d
Revises: 9f842f526300
Create Date: 2026-07-11 17:16:06.425449

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5c8e2aeaa48d"
down_revision: str | None = "9f842f526300"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting_sessions",
        sa.Column("speaker_names_json", sa.Text(), server_default="{}", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting_sessions", "speaker_names_json")
    # ### end Alembic commands ###
