"""add skill enablement columns

Revision ID: 64f57b15c12d
Revises: df4618970b0e
Create Date: 2026-06-26 09:58:33.593575

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "64f57b15c12d"
down_revision: str | None = "df4618970b0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("skills", sa.Column("enabled", sa.Boolean(), server_default="0", nullable=False))
    op.add_column("skills", sa.Column("migrated", sa.Boolean(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skills", "migrated")
    op.drop_column("skills", "enabled")
    # ### end Alembic commands ###
