"""add agent_schedule

Revision ID: 949c707eb929
Revises: a5eb51059e1e
Create Date: 2026-06-30 09:24:48.376996

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "949c707eb929"
down_revision: str | None = "a5eb51059e1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_session_id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("clear_context", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("run_at_minute", sa.Integer(), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("days_of_week", sa.Integer(), server_default="127", nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="idle", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_session_id"], ["agent_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_schedule_agent_session_id"),
        "agent_schedule",
        ["agent_session_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_agent_schedule_next_run_at"), "agent_schedule", ["next_run_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_schedule_next_run_at"), table_name="agent_schedule")
    op.drop_index(op.f("ix_agent_schedule_agent_session_id"), table_name="agent_schedule")
    op.drop_table("agent_schedule")
    # ### end Alembic commands ###
