"""add notes to meeting_sessions

Revision ID: 9633c13db421
Revises: 38e2b7f39f6c
Create Date: 2026-07-12 12:31:46.412387

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9633c13db421"
down_revision: str | None = "38e2b7f39f6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting_sessions", sa.Column("notes", sa.Text(), server_default="", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting_sessions", "notes")
    # ### end Alembic commands ###
