"""add message model and elapsed_ms

Revision ID: a5eb51059e1e
Revises: 64f57b15c12d
Create Date: 2026-06-26 11:42:18.751967

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a5eb51059e1e"
down_revision: str | None = "64f57b15c12d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("model", sa.Text(), nullable=True))
    op.add_column("messages", sa.Column("elapsed_ms", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "elapsed_ms")
    op.drop_column("messages", "model")
    # ### end Alembic commands ###
