"""add agent active_prompt and streaming columns

Revision ID: c04d5ffe8e4c
Revises: 2b00968ac335
Create Date: 2026-06-23 20:50:11.928961

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c04d5ffe8e4c"
down_revision: str | None = "2b00968ac335"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_sessions", sa.Column("active_prompt", sa.Text(), nullable=True))
    op.add_column(
        "agent_sessions", sa.Column("streaming", sa.Boolean(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_sessions", "streaming")
    op.drop_column("agent_sessions", "active_prompt")
    # ### end Alembic commands ###
