"""add message suggestions

Revision ID: df4618970b0e
Revises: 0ab504427707
Create Date: 2026-06-24 19:10:14.761310

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "df4618970b0e"
down_revision: str | None = "0ab504427707"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("suggestions", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "suggestions")
    # ### end Alembic commands ###
