"""add topic summaries

Revision ID: f1e3c30b32f5
Revises: e885c0ff0be7
Create Date: 2026-09-11 21:00:36.123827

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f1e3c30b32f5"
down_revision: str | None = "e885c0ff0be7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("visible", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("user_edited", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pending_content", sa.Text(), nullable=True),
        sa.Column("pending_model", sa.String(length=128), nullable=True),
        sa.Column("pending_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topic_summaries_topic_id"), "topic_summaries", ["topic_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topic_summaries_topic_id"), table_name="topic_summaries")
    op.drop_table("topic_summaries")
    # ### end Alembic commands ###
